/*
 ANIMAL_INS, ANIMAL_OUTS  // ANIMAL_ID 외래키

 1. ANIMAL_OUTS 에는 있는데 ANIMAL_INS 에는 기록이 없는 것 찾기
 2. 출력 대상 : ANIMAL_ID / NAME

 LEFT JOIN
*/


SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_OUTS AO
LEFT JOIN ANIMAL_INS AI
ON AO.ANIMAL_ID = AI.ANIMAL_ID
WHERE AI.ANIMAL_ID IS NULL

