/*
    ANIMAL_INS : 보호소에 들어온 동물의 정보
    ANIMAL_OUTS : 입양을 간 정보

    - 보호 시작일(DATETIME) 보다 입양일(DATETIME)이 더 빠른
    - 동물의 ANIMAL_ID 와 NAME을 조회
    - 보호 시작일을 ORDER BY ASC
*/

SELECT AI.ANIMAL_ID, AI.NAME
FROM ANIMAL_INS AI
LEFT JOIN ANIMAL_OUTS AO
ON AI.ANIMAL_ID = AO.ANIMAL_ID
WHERE AI.DATETIME > AO.DATETIME
ORDER BY AI.DATETIME
